// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uibtorxyhvysvuwvcsuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpYnRvcnh5aHZ5c3Z1d3Zjc3V5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNjEzMTIsImV4cCI6MjA2MDczNzMxMn0.bukL10A9bqjWA0sfS3HTBX8e5sEoVPJW6LW8ouGaPuc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);